version: '3.9'

services:
  app:
    build: .
    container_name: mbf-backend
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:nodemon
    environment:
      - NODE_ENV=development
